apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: container3
              image: nginx
          restartPolicy: Never
~                                                                                                                                                                                                          
~                           
